#!/bin/bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

scripts=$HOME/.config/scripts

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Q spawn ghostty

# Super+Q to close the focused view
riverctl map normal Super C close

# Super+Shift+E to exit river
riverctl map normal Super+Alt M exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super H focus-view left
riverctl map normal Super L focus-view right

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift L swap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Control H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume spawn "${scripts}/volume.sh --up"
    riverctl map $mode None XF86AudioLowerVolume spawn "${scripts}/volume.sh --down"
    riverctl map $mode None XF86AudioMute spawn "${scripts}/mute-toggle.sh"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp spawn "${scripts}/bright.sh --up"
    riverctl map $mode None XF86MonBrightnessDown spawn "${scripts}/bright.sh --down"
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0xc8c093
riverctl border-color-unfocused 0xFF000000
riverctl border-width 2

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 2 &

riverctl keyboard-layout pt

riverctl input pointer-1739-52772-SYNA32B0:00_06CB:CE24_Touchpad natural-scroll enabled

riverctl map normal Super F toggle-fullscreen
riverctl map normal Super+Shift F toggle-float

riverctl map normal Super R spawn "${scripts}/wofi.sh"
riverctl map normal Super W spawn "${scripts}/popup_waybar.sh"
riverctl map normal Super+Shift W spawn "${scripts}/persistent_waybar.sh"

riverctl rule-add ssd

riverctl spawn dunst
riverctl spawn waybar &&
    riverctl spawn blueman-applet
riverctl spawn nm-applet
riverctl spawn swayosd-server
riverctl spawn 'swww-daemon'
riverctl spawn 'swww img /usr/share/backgrounds/hyprpaper.jpg'
