-- Generated by nwg-displays on 2026-06-29 at 13:12:43. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.03",
    position = "5142x703",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "3440x1440@59.97",
    position = "7062x0",
    scale = 1.0
})
